#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    n = None  # TODO: edit here
    a = [None for _ in range(n - 1)]
    b = [None for _ in range(n - 1)]
    for i in range(n - 1):
        a[i] = None  # TODO: edit here
        b[i] = None  # TODO: edit here
    q = None  # TODO: edit here
    query = [None for _ in range(q)]
    for i in range(q):
        query[i] = None  # TODO: edit here
    print(n)
    for i in range(n - 1):
        print(a[i], b[i])
    print(q)
    for i in range(q):
        print(query[i])

if __name__ == "__main__":
    main()
