#!/usr/bin/env python3
# from typing import *



# def solve(N: int, u: List[int], v: List[int], Q: int, A: List[int], B: List[int]) -> int:
def solve(N, u, v, Q, A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    u = [None for _ in range(N - 1)]
    v = [None for _ in range(N - 1)]
    for i in range(N - 1):
        u[i], v[i] = map(int, input().split())
    Q = int(input())
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        A[i], B[i] = map(int, input().split())
    a = solve(N, u, v, Q, A, B)
    print(a)

if __name__ == '__main__':
    main()
