#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, A: List[int], B: List[int], C: List[int]) -> List[str]:
def solve(N, M, A, B, C):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.4.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i], C[i] = map(int, input().split())
    ans = solve(N, M, A, B, C)
    for i in range(M):
        print(ans[i])

if __name__ == '__main__':
    main()
